---
# tasks file for projectprovisioner
- name: Fetch Repository
  git:
    repo: "{{ project_definition_git }}"
    dest: /tmp/checkout

- name: include variables from git repo
  include_vars:
    file: /tmp/checkout/projects.yaml

- include_tasks: project-provision.yml
  loop: "{{ projects }}"
  loop_control:
    loop_var: current_project

- include_tasks: project-deprovision.yaml
  loop: "{{ projects }}"
  loop_control:
    loop_var: current_project
  when: current_project.deprovision