---
# tasks file for projectprovisioner
- name: Fetch Repository
  git:
    repo: "{{ project-definion-git }}"
    dest: /tmp/checkout
    version: Master

- name: include variables from git repo
  include_vars:
    file: /tmp/checkout/projects.yaml

- name: Create Projects based on definition
  k8s:
    definition:
      apiVersion: project.openshift.io/v1
      kind: Projects
      metadata:
        name: "{{ item.name }}"
  loop: "{{ projects }}"