- name: Fetch project pods
  k8s_facts:
    api_version: v1
    kind: Pod
    namespace: "{{ current_namespace.name }}"
  register: namespace_pods

- name: Deleting empty project
  k8s:
    name: "{{ current_namespace.name }}"
    api_version: v1
    kind: Namespace
    state: absent
  when: namespace_pods.resources[0] is not defined

- name: Project not empty - change description
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        annotations:
          openshift.io/display-name: "! MARKED FOR DELETION !"
          openshift.io/description: ""
        labels:
          deprovision: "true"
        name: "{{ current_project.name }}"
  when: namespace_pods.resources[0] is defined