- name: Create Projects based on definition
  k8s:
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: "{{ current_project.name }}"
      spec:
        finalizers:
        - kubernetes

- name: Update Project/Namespace annotations
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        annotations:
          company.org/owner: "{{ current_project.owner | default('') }}"
          company.org/owner-email: "{{ current_project.ownerMail | default('') }}"
        name: "{{ current_project.name }}"
      spec:
        finalizers:
        - kubernetes

- name: Add Rolebindings for users or groups
  k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: "{{ current_project.name }}-{{ item.role }}"
        namespace: "{{ current_project.name }}"
      subjects:
        - kind: "{{ item.kind }}"
          apiGroup: rbac.authorization.k8s.io
          name: "{{ item.subjectName }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: "{{ item.role }}"
  loop: "{{ current_project.access }}"
  when: current_project.access is defined

