apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projectprovisioners.project-provisioner.io
spec:
  group: project-provisioner.io
  names:
    kind: ProjectProvisioner
    listKind: ProjectProvisionerList
    plural: projectprovisioners
    singular: projectprovisioner
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
