kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-provisioner
subjects:
- kind: ServiceAccount
  name: project-provisioner
  namespace:
roleRef:
  kind: ClusterRole
  name: project-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-self-provisioner
subjects:
  - kind: ServiceAccount
    name: project-provisioner
    namespace: 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner
