kind: CLusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-provisioner
subjects:
- kind: ServiceAccount
  name: project-provisioner
roleRef:
  kind: ClusterRole
  name: project-provisioner
  apiGroup: rbac.authorization.k8s.io
